<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>North Ryde Soccer Club</title>
		<meta name="robots" content="all" />
		<meta name="viewport" content="width=800" />
        <meta http-equiv="X-UA-Compatible" content="IE=100" />
		<link rel="Shortcut Icon" type="image/x-icon" href="favicon.ico" />
		<link rel="canonical" href="http://www.northrydesoccer.com.au/admin" />
		<link rel="stylesheet" type="text/css" href="_Resources/ddsmoothmenu.css" />
		<link rel="stylesheet" type="text/css" href="stylesheets/main.css" /><!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="stylesheets/ie8.css" /><![endif]-->
		
		<!--script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.4.min.js"></script-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
		
<link rel="stylesheet" href="stylesheets/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />
<script src="javascript/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>


<script id="ddsmoothmenu" src="_Resources/ddsmoothmenu.js">
/***********************************************
* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/
</script><script>
ddsmoothmenu.arrowimages = {down:['downarrowclass', '_Resources/down.gif', 23], right:['rightarrowclass', '_Resources/right.gif']}
ddsmoothmenu.init({ mainmenuid: 'sitemenu-content',orientation:'h', classname:'ddsmoothmenu',contentsource:'markup'})
</script>
	</head>
	<body class="sandvox has-page-title no-sidebar no-custom-banner no-navigation no-IR" id="NorthRydeSoccer" >
		<div id="page-container">
			<div id="page">
				<div id="page-top" class="has-logo has-title has-tagline">
					<div id="title">
						<div id="logo">
						<span ><img id="logo" width="540" height="150" src="_Media/nrs_emblem.gif" alt="" /></span>
						</div>
						<div id="heading">
						<span ><img id="heading" width="540" height="150" src="_Media/header1.gif" alt="" /></span>
						</div>
						<p id="tagline"><span class="in"></span></p>
					</div><!-- title -->