<tr>
      <td>
        <table cellspacing="0" cellpadding="0">
        <tr>
          <td class="sitemenu"><a class="sitemenulink" href="/index.php">&nbsp;Front Page&nbsp;</a></td>
          <td class="sitemenu"><a class="sitemenulink" href="/sponsors.php">&nbsp;Sponsors&nbsp;</a></td>
          <td class="sitemenu"><a class="sitemenulink" href="/weather.php">&nbsp;Weather&nbsp;</a></td>
          <td class="sitemenu"><a class="sitemenulink" href="/site_map.php">&nbsp;Site Map&nbsp;</a></td>
          <td class="sitemenu"><a class="sitemenulink" href="mailto:admin@northrydesoccer.com.au?subject=NRSC Feedback">&nbsp;Feedback&nbsp;</a>
        </tr>
        </table>
      </td>
    </tr>