<div class="clear below-content"></div>
				<div id="page-bottom">
					<div id="page-bottom-contents">
						<div>© Ricky Symonds 2013</div>
						<div class="hidden"> <a rel="nofollow" href="#title">[Back To Top]</a></div>
					</div>
				</div> <!-- page-bottom -->
			</div> <!-- container -->
			<div id="extraDiv1"><span></span></div><div id="extraDiv2"><span></span></div><div id="extraDiv3"><span></span></div><div id="extraDiv4"><span></span></div><div id="extraDiv5"><span></span></div><div id="extraDiv6"><span></span></div>
		</div> <!-- specific body type -->
	</body>
</html>