<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>News Admin | North Ryde Soccer Club</title>
		<meta name="robots" content="all" />
		<meta name="viewport" content="width=800" />
        <meta http-equiv="X-UA-Compatible" content="IE=100" />
		<link rel="Shortcut Icon" type="image/x-icon" href="favicon.ico" />
		<link rel="canonical" href="http://www.northrydesoccer.com.au/admin" />
		<link rel="stylesheet" type="text/css" href="/stylesheets/main.css" /><!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="stylesheets/ie8.css" /><![endif]-->
		
		<script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.5.2.min.js"></script><script>
if (typeof jQuery === 'undefined') document.write('<script src="/_Resources/jquery-1.5.2.min.js"><\/script>');
</script>
	</head>
	<body class="sandvox has-page-title allow-sidebar no-custom-banner  home-page no-IR" id="NorthRydeSoccer" >
		<div id="page-container">
			<div id="page">
				<div id="page-top" class="has-logo has-title has-tagline">
					<div id="title">
						<div id="logo">
						<span ><img id="logo" width="540" height="150" src="/_Media/nrs_emblem.gif" alt="" /></span>
						</div>
						<div id="heading">
						<span ><img id="heading" width="540" height="150" src="/_Media/header1.gif" alt="" /></span>
						</div>
						<p id="tagline"><span class="in"></span></p>
					</div><!-- title -->