<div id="sitemenu-container">
						<div id="sitemenu">
	<h2 class="hidden">Site Navigation<a href="#page-content" rel="nofollow">[Skip]</a></h2>
	<div id="sitemenu-content">
		<ul>
			<li class="i1 o <?php echo ($currentPage == 'HOME' ? 'currentPage"><span class="in">Home</span></li>' : '"><a href="index.php" title="About NRSC"><span class="in">Home</span></a></li>') ?>
			<li class="i2 e <?php echo ($currentPage == 'ABOUT' ? 'currentPage"><span class="in">About NRSC</span></li>' : '"><a href="about.php" title="About NRSC"><span class="in">About NRSC</span></a></li>') ?>
			<li class="i3 o hasSubmenu <?php echo ($currentPage == 'PLAYER' ? 'currentPage"><span class="in">Player Information</span>' : '"><a href="#" title="Player Information"><span class="in">Player Information</span></a>') ?>
				<ul class="isSubMenu">
					<li class="i1 o <?php echo ($currentPage == 'TRAINING' ? 'currentPage"><span class="in">Training</span></li>' : '"><a href="training.php" title="Training"><span class="in">Training</span></a></li>') ?>
					<li class="i1 o <?php echo ($currentPage == 'GROUNDS' ? 'currentPage"><span class="in">Grounds</span></li>' : '"><a href="grounds.php" title="Grounds"><span class="in">Grounds</span></a></li>') ?>
					<li class="i1 o <?php echo ($currentPage == 'LIBRARY' ? 'currentPage"><span class="in">Library</span></li>' : '"><a href="library.php" title="Library"><span class="in">Library</span></a></li>') ?>
					<li class="i1 o <?php echo ($currentPage == 'WEATHER' ? 'currentPage"><span class="in">Wet Weather</span></li>' : '"><a href="weather.php" title="Wet Weather"><span class="in">Wet Weather</span></a></li>') ?>
				</ul>
			</li>
			<li class="i4 e <?php echo ($currentPage == 'FIXTURES' ? 'currentPage"><span class="in">Fixtures & Results</span></li>' : '"><a href="fixtures.php" title="Fixtures & Results"><span class="in">Fixtures & Results</span></a></li>') ?>
			<li class="i5 o hasSubmenu last <?php echo ($currentPage == 'CONTACT' ? 'currentPage"><span class="in">Contact Us</span>' : '"><a href="contacts.php" title="Contact Us"><span class="in">Contact Us</span></a>') ?>
				<ul class="isSubMenu">
					<li class="i1 o <?php echo ($currentPage == 'FAQ' ? 'currentPage"><span class="in">FAQ</span></li>' : '"><a href="faq.php" title="FAQ"><span class="in">FAQ</span></a></li>') ?>
					<li class="i1 o <?php echo ($currentPage == 'SPONSORS' ? 'currentPage"><span class="in">Sponsors</span></li>' : '"><a href="sponsors.php" title="Sponsors"><span class="in">Sponsors</span></a></li>') ?>
				</ul>
			</li>
		</ul>
	</div> <!-- /sitemenu-content -->
</div> <!-- /sitemenu -->
					</div> <!-- sitemenu-container -->
				</div> <!-- page-top -->